@Schedoo.Server_HostAddress = http://localhost:5153
@RefServer_Address = http://fmi-schedule.chnu.edu.ua

GET {{Schedoo.Server_HostAddress}}/groupschedule
Accept: application/json

###

GET {{RefServer_Address}}/public/semesters
Accept: application/json
